name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-slim
    timeout-minutes: 15
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: dependabot/fetch-metadata@v3.1.0
        id: metadata
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
